# Generated by Django 4.0.4 on 2022-05-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zip_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name', 'first_name'], name='store.custo_last_na_91d0f5_idx'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='store.customers',
        ),
    ]
